id: P003153
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6549
  title: བོད་ལྗོངས་སློབ་ཆེན་རིག་གཞུང་སློབ་གླིང་གི་ཞིབ་འཇུག་སློབ་མའི་དཔྱད་རྩོམ་གཅེས་བསྡུས།
  author: ''
  volumes:
    fa24630057f94500a40a0177a750eb8f:
      image_group_id: I3CN8693
      title: ''
      volume_number: 1
      total_pages: 220
